require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/refund_requests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RefundRequest. As you add validations to RefundRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RefundRequest.create! valid_attributes
      get refund_requests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      refund_request = RefundRequest.create! valid_attributes
      get refund_request_url(refund_request)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_refund_request_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      refund_request = RefundRequest.create! valid_attributes
      get edit_refund_request_url(refund_request)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RefundRequest" do
        expect {
          post refund_requests_url, params: { refund_request: valid_attributes }
        }.to change(RefundRequest, :count).by(1)
      end

      it "redirects to the created refund_request" do
        post refund_requests_url, params: { refund_request: valid_attributes }
        expect(response).to redirect_to(refund_request_url(RefundRequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RefundRequest" do
        expect {
          post refund_requests_url, params: { refund_request: invalid_attributes }
        }.to change(RefundRequest, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post refund_requests_url, params: { refund_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested refund_request" do
        refund_request = RefundRequest.create! valid_attributes
        patch refund_request_url(refund_request), params: { refund_request: new_attributes }
        refund_request.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the refund_request" do
        refund_request = RefundRequest.create! valid_attributes
        patch refund_request_url(refund_request), params: { refund_request: new_attributes }
        refund_request.reload
        expect(response).to redirect_to(refund_request_url(refund_request))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        refund_request = RefundRequest.create! valid_attributes
        patch refund_request_url(refund_request), params: { refund_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested refund_request" do
      refund_request = RefundRequest.create! valid_attributes
      expect {
        delete refund_request_url(refund_request)
      }.to change(RefundRequest, :count).by(-1)
    end

    it "redirects to the refund_requests list" do
      refund_request = RefundRequest.create! valid_attributes
      delete refund_request_url(refund_request)
      expect(response).to redirect_to(refund_requests_url)
    end
  end
end
